name: Build docker containers
on:
  push:
    branches:
      - main
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - run: echo CONTAINER_REPO=ghcr.io/micromaomao/sleep.maowtm.org >> $GITHUB_ENV
      - name: Build main service
        run: docker build . -t $CONTAINER_REPO/app:${{ github.sha }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: |
          set -e
          for image in app; do
            docker push $CONTAINER_REPO/${image}:${{ github.sha }}
            docker tag $CONTAINER_REPO/${image}:${{ github.sha }} $CONTAINER_REPO/${image}:latest
            docker push $CONTAINER_REPO/${image}:latest
          done
