name: Build docker containers
on:
  push:
    branches:
      - main
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build main service
        run: docker build . -t ghcr.io/${{ github.repository }}/app:${{ github.sha }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: |
          set -e
          for image in app; do
            docker push ghcr.io/${{ github.repository }}/${image}:${{ github.sha }}
            docker tag ghcr.io/${{ github.repository }}/${image}:${{ github.sha }} ghcr.io/${{ github.repository }}/${image}:latest
            docker push ghcr.io/${{ github.repository }}/${image}:latest
          done
